services:
  backend:
    build: ./backend
    image: linopix/ets2-backend:latest
    container_name: ets2-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - ./data:/data
    ports:
      - "3001:3001"

  frontend:
    image: nginx:alpine
    container_name: ets2-frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "2006:80"